version: '3.8'

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-db}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data

  pg_proxy:
    platform: linux/amd64
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: 'db:5432'
      ALLOW_ADDR_REGEX: '.*'
      LOG_TRAFFIC: 'true'
    ports:
      - '5433:80'
    depends_on:
      - db

volumes:
  db-data:
